local Library = loadstring(game:HttpGet(
                               "https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib(
                   "Mistypeak Gui Made By ɹɐʇsɓuᴉuɹoW ɐuᴉɹqɐS",
                   "Sentinel")

local Tab = Window:NewTab("Mistypeak Shop")
local Section = Tab:NewSection("Raven Set")

Section:NewButton("Raven Clothes", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Raven",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Raven Face", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "raven face",
        [2] = "Faces"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)
        
Section:NewButton("Raven  Hair", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Raven Hood",
        [2] = "Hair"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Bloom Set")

Section:NewButton("Bloom Clothes", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "bloom2",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Bloom Face", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Bloom Face",
        [2] = "Faces"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)
        
Section:NewButton("Bloom Hair", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Bloom Hair",
        [2] = "Hair"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Bloom Wings", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Winx2",
        [2] = "Wings"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Starfire Set")

Section:NewButton("Starfire Clothes", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Starfire",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Starfire Face", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Starfire Face",
        [2] = "Faces"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)
        
Section:NewButton("Starfire Hair", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Starfire Hair",
        [2] = "Hair"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Zuko Set")

Section:NewButton("Zuko Clothes", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Zuko",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Zuko Face", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Zuko Face",
        [2] = "Faces"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Zuko Hair", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Zuko Hair",
        [2] = "Hair"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Danny Phantom Set")

Section:NewButton("Danny Phantom Clothes", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Danny Phantom",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Danny Phantom Face", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Danny Phantom Face",
        [2] = "Faces"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)
        
Section:NewButton("Danny Phantom Hair", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Danny Phantom Hair",
        [2] = "Hair"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Chat Noir Set")

Section:NewButton("Chat Noir Clothes", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Chat Noir",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Chat Noir Face", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Chat Noir Face",
        [2] = "Faces"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)
        
Section:NewButton("Chat Noir Hair", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Chat Noir Hair",
        [2] = "Hair"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Victorian Dresses")

Section:NewButton("Victorian Dress 1/Red", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "VictorianDress",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)


Section:NewButton("Victorian Dress 2/Green", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "VictorianDress2",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Victorian Dress 3/Black", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "VictorianDress3",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)


Section:NewButton("Victorian Dress 4/Pink", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "VictorianDress4",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Victorian Dress 5/Blue", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "VictorianDress5",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)


Section:NewButton("Victorian Dress 6/Violet", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "VictorianDress6",
        [2] = "Clothing"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Victorian Accessories")

Section:NewButton("Victorian Headpiece", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Victorian Headpiece",
        [2] = "Accessories"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Victorian Headpiece 1", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "Victorian Headpiece1",
        [2] = "Accessories"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Section = Tab:NewSection("Tiara's")

Section:NewButton("Lower Tiara", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "LowerTiara",
        [2] = "Accessories"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Lower Tiara Green", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "LowerTiaraGreen",
        [2] = "Accessories"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Lower Tiara Pink", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "LowerTiaraPink",
        [2] = "Accessories"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

Section:NewButton("Lower Tiara Red", "", function()
    -- Script generated by SimpleSpy - credits to exx#9394
    
    
    local args = {
        [1] = "LowerTiaraRed",
        [2] = "Accessories"
    }
    
    game:GetService("ReplicatedStorage").BuyItem:InvokeServer(unpack(args))
end)

local Tab = Window:NewTab("Tp")
local Section = Tab:NewSection("Locations")

Section:NewButton("Gifts Leaderboard", "", function()
    game.Players.LocalPlayer.Character:MoveTo(Vector3.new(-1036, 81, -3538))
end)

Section:NewButton("Winter Event", "", function()
    game.Players.LocalPlayer.Character:MoveTo(Vector3.new(290, 81, -3051))
end)

local Tab = Window:NewTab("Other")
local Section = Tab:NewSection("Misc")

Section:NewTextBox("Teleport", "", function(txt)
    local Players = game:GetService("Players")
    local msg = txt
    local function findPlayer(stringg)
        for _, v in pairs(Players:GetPlayers()) do
            if stringg:lower() == (v.Name:lower()):sub(1, #stringg) then
                return v
            end
        end
    end

    local player = findPlayer(msg)
    local CHAR = player.Character
    local msg = txt
    local function findPlayer(stringg)
        for _, v in pairs(Players:GetPlayers()) do
             if stringg:lower() == (v.Name:lower()):sub(1, #stringg) then
                   return v
             end
        end
    end
    
    local player = findPlayer(msg)
    game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = player.Character.HumanoidRootPart.CFrame
end)

Section:NewButton("Infinite Yield", "Admin", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)

Section:NewButton("Btools", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/TheMorningstarCircle/Spellman/main/Btools"))()
end)

Section:NewButton("CMD Admin", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/TheMorningstarCircle/Spellman/main/CMD"))()
end)

Section:NewButton("Dark Dex", "Dex", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/TheMorningstarCircle/Spellman/main/Dex"))()
end)

Section:NewButton("Simple Spy", "Remote Spy", function()
    loadstring(game:HttpGet("https://github.com/exxtremestuffs/SimpleSpySource/raw/master/SimpleSpy.lua"))()
end)

Section:NewButton("Hydroxide", "Remote Spy", function()
    loadstring(game:HttpGetAsync('https://raw.githubusercontent.com/TheMorningstarCircle/Spellman/main/Hydroxide', true))()
end)

Section:NewButton("In-Line Translator", "Translate", function()
    loadstring(game:HttpGetAsync('https://i.qts.life/r/ChatInlineTranslator.lua', true))()
end)

local Tab = Window:NewTab("Credits")
local Section = Tab:NewSection("Created by ɹɐʇsɓuᴉuɹoW ɐuᴉɹqɐS")

local Section = Tab:NewSection("Toggle UI")
Section:NewKeybind("Toggle UI", "Toggle UI", Enum.KeyCode.Zero, function()
	Library:ToggleUI()
end)

wait(1)
game.StarterGui:SetCore("SendNotification", { 
    Title = "★ᵀʰᵉ ᴹᵒʳⁿⁱⁿᵍˢᵗᵃʳ ᶜⁱʳᶜˡᵉ★";
    Text = "Mistypeak GUI                ~~~~~~ Now Active ~~~~~~";               
    Icon = "rbxthumb://type=Asset&id=10845688213&w=150&h=150";
    Duration = "60";
    Button1 = "Close";
})

    
    

    
    